import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:gahurakshak/core/constants/locale_keys.dart';
import 'package:gahurakshak/core/routes/routes.dart';
import 'package:gahurakshak/core/theme/app_color_theme.dart';
import 'package:gahurakshak/core/theme/app_text_theme.dart';
import 'package:gahurakshak/core/utils/size_utils.dart';
import 'package:gahurakshak/core/widgets/app_bar/custom_app_bar.dart';
import 'package:gahurakshak/features/dashboard/presenatation/data/models/ml_data_models.dart';
import 'package:lucide_icons/lucide_icons.dart';

class DashBoardBody extends StatelessWidget {
  DashBoardBody({super.key});

  final List<Map<String, dynamic>> modelDetailList = [
    {
      "title": "VGG-16",
      "modelData": [
        MLDataModel(
          index: 0,
          title: "VGG-16",
          label1: "train",
          label2: "validation",
          lineChartmodelData: {
            "train": [
              EchopsWithAccuracyModel(echops: 0, accuracy: 0.50),
              EchopsWithAccuracyModel(echops: 1, accuracy: 0.55),
              EchopsWithAccuracyModel(echops: 2, accuracy: 0.60),
              EchopsWithAccuracyModel(echops: 3, accuracy: 0.63),
              EchopsWithAccuracyModel(echops: 4, accuracy: 0.65),
              EchopsWithAccuracyModel(echops: 5, accuracy: 0.70),
              EchopsWithAccuracyModel(echops: 6, accuracy: 0.73),
              EchopsWithAccuracyModel(echops: 7, accuracy: 0.75),
              EchopsWithAccuracyModel(echops: 8, accuracy: 0.78),
              EchopsWithAccuracyModel(echops: 9, accuracy: 0.80),
              EchopsWithAccuracyModel(echops: 10, accuracy: 0.82),
              EchopsWithAccuracyModel(echops: 11, accuracy: 0.83),
              EchopsWithAccuracyModel(echops: 12, accuracy: 0.85),
              EchopsWithAccuracyModel(echops: 13, accuracy: 0.86),
              EchopsWithAccuracyModel(echops: 14, accuracy: 0.87),
              EchopsWithAccuracyModel(echops: 15, accuracy: 0.88),
              EchopsWithAccuracyModel(echops: 16, accuracy: 0.89),
              EchopsWithAccuracyModel(echops: 17, accuracy: 0.90),
              EchopsWithAccuracyModel(echops: 18, accuracy: 0.91),
              EchopsWithAccuracyModel(echops: 19, accuracy: 0.92),
            ],
            "validation": [
              EchopsWithAccuracyModel(echops: 0, accuracy: 0.50),
              EchopsWithAccuracyModel(echops: 1, accuracy: 0.52),
              EchopsWithAccuracyModel(echops: 2, accuracy: 0.55),
              EchopsWithAccuracyModel(echops: 3, accuracy: 0.57),
              EchopsWithAccuracyModel(echops: 4, accuracy: 0.58),
              EchopsWithAccuracyModel(echops: 5, accuracy: 0.60),
              EchopsWithAccuracyModel(echops: 6, accuracy: 0.62),
              EchopsWithAccuracyModel(echops: 7, accuracy: 0.63),
              EchopsWithAccuracyModel(echops: 8, accuracy: 0.65),
              EchopsWithAccuracyModel(echops: 9, accuracy: 0.67),
              EchopsWithAccuracyModel(echops: 10, accuracy: 0.68),
              EchopsWithAccuracyModel(echops: 11, accuracy: 0.69),
              EchopsWithAccuracyModel(echops: 12, accuracy: 0.70),
              EchopsWithAccuracyModel(echops: 13, accuracy: 0.72),
              EchopsWithAccuracyModel(echops: 14, accuracy: 0.73),
              EchopsWithAccuracyModel(echops: 15, accuracy: 0.74),
              EchopsWithAccuracyModel(echops: 16, accuracy: 0.75),
              EchopsWithAccuracyModel(echops: 17, accuracy: 0.76),
              EchopsWithAccuracyModel(echops: 18, accuracy: 0.77),
              EchopsWithAccuracyModel(echops: 19, accuracy: 0.78),
            ]
          },
          chartTitle: "Train vs Validation Accuracy",
        ),
        MLDataModel(
          title: "VGG-16",
          index: 0,
          label1: "train",
          label2: "validation",
          lineChartmodelData: {
            "train": [
              EchopsWithAccuracyModel(echops: 19, accuracy: 1.20),
              EchopsWithAccuracyModel(echops: 18, accuracy: 1.10),
              EchopsWithAccuracyModel(echops: 17, accuracy: 1.00),
              EchopsWithAccuracyModel(echops: 16, accuracy: 0.90),
              EchopsWithAccuracyModel(echops: 15, accuracy: 0.80),
              EchopsWithAccuracyModel(echops: 14, accuracy: 0.70),
              EchopsWithAccuracyModel(echops: 13, accuracy: 0.70),
              EchopsWithAccuracyModel(echops: 12, accuracy: 0.60),
              EchopsWithAccuracyModel(echops: 11, accuracy: 0.60),
              EchopsWithAccuracyModel(echops: 10, accuracy: 0.50),
              EchopsWithAccuracyModel(echops: 9, accuracy: 0.50),
              EchopsWithAccuracyModel(echops: 8, accuracy: 0.50),
              EchopsWithAccuracyModel(echops: 7, accuracy: 0.40),
              EchopsWithAccuracyModel(echops: 6, accuracy: 0.40),
              EchopsWithAccuracyModel(echops: 5, accuracy: 0.40),
              EchopsWithAccuracyModel(echops: 4, accuracy: 0.30),
              EchopsWithAccuracyModel(echops: 3, accuracy: 0.30),
              EchopsWithAccuracyModel(echops: 2, accuracy: 0.30),
              EchopsWithAccuracyModel(echops: 1, accuracy: 0.20),
              EchopsWithAccuracyModel(echops: 0, accuracy: 0.20),
            ],
            "validation": [
              EchopsWithAccuracyModel(echops: 19, accuracy: 1.20),
              EchopsWithAccuracyModel(echops: 18, accuracy: 1.10),
              EchopsWithAccuracyModel(echops: 17, accuracy: 1.00),
              EchopsWithAccuracyModel(echops: 16, accuracy: 0.90),
              EchopsWithAccuracyModel(echops: 15, accuracy: 0.80),
              EchopsWithAccuracyModel(echops: 14, accuracy: 0.80),
              EchopsWithAccuracyModel(echops: 13, accuracy: 0.70),
              EchopsWithAccuracyModel(echops: 12, accuracy: 0.70),
              EchopsWithAccuracyModel(echops: 11, accuracy: 0.60),
              EchopsWithAccuracyModel(echops: 10, accuracy: 0.60),
              EchopsWithAccuracyModel(echops: 9, accuracy: 0.60),
              EchopsWithAccuracyModel(echops: 8, accuracy: 0.50),
              EchopsWithAccuracyModel(echops: 7, accuracy: 0.50),
              EchopsWithAccuracyModel(echops: 6, accuracy: 0.50),
              EchopsWithAccuracyModel(echops: 5, accuracy: 0.40),
              EchopsWithAccuracyModel(echops: 4, accuracy: 0.40),
              EchopsWithAccuracyModel(echops: 3, accuracy: 0.40),
              EchopsWithAccuracyModel(echops: 2, accuracy: 0.40),
              EchopsWithAccuracyModel(echops: 1, accuracy: 0.30),
              EchopsWithAccuracyModel(echops: 0, accuracy: 0.30),
            ]
          },
          chartTitle: "Train vs Validation Loss",
        ),
      ],
    },
    {
      "title": "CNN-30",
      "modelData": [
        MLDataModel(
          index: 1,
          title: "CNN-30",
          label1: "train",
          label2: "validation",
          lineChartmodelData: {
            "train": [
              EchopsWithAccuracyModel(echops: 0, accuracy: 0.46),
              EchopsWithAccuracyModel(echops: 1, accuracy: 0.61),
              EchopsWithAccuracyModel(echops: 2, accuracy: 0.64),
              EchopsWithAccuracyModel(echops: 3, accuracy: 0.68),
              EchopsWithAccuracyModel(echops: 4, accuracy: 0.71),
              EchopsWithAccuracyModel(echops: 5, accuracy: 0.72),
              EchopsWithAccuracyModel(echops: 6, accuracy: 0.73),
              EchopsWithAccuracyModel(echops: 7, accuracy: 0.73),
              EchopsWithAccuracyModel(echops: 8, accuracy: 0.75),
              EchopsWithAccuracyModel(echops: 9, accuracy: 0.76),
              EchopsWithAccuracyModel(echops: 10, accuracy: 0.75),
              EchopsWithAccuracyModel(echops: 11, accuracy: 0.77),
              EchopsWithAccuracyModel(echops: 12, accuracy: 0.76),
              EchopsWithAccuracyModel(echops: 13, accuracy: 0.77),
              EchopsWithAccuracyModel(echops: 14, accuracy: 0.78),
              EchopsWithAccuracyModel(echops: 15, accuracy: 0.79),
              EchopsWithAccuracyModel(echops: 16, accuracy: 0.77),
              EchopsWithAccuracyModel(echops: 17, accuracy: 0.79),
              EchopsWithAccuracyModel(echops: 18, accuracy: 0.79),
              EchopsWithAccuracyModel(echops: 19, accuracy: 0.80),
              EchopsWithAccuracyModel(echops: 20, accuracy: 0.80),
              EchopsWithAccuracyModel(echops: 21, accuracy: 0.80),
              EchopsWithAccuracyModel(echops: 22, accuracy: 0.80),
              EchopsWithAccuracyModel(echops: 23, accuracy: 0.80),
              EchopsWithAccuracyModel(echops: 24, accuracy: 0.86),
              EchopsWithAccuracyModel(echops: 25, accuracy: 0.81),
              EchopsWithAccuracyModel(echops: 26, accuracy: 0.81),
              EchopsWithAccuracyModel(echops: 27, accuracy: 0.81),
              EchopsWithAccuracyModel(echops: 28, accuracy: 0.81),
              EchopsWithAccuracyModel(echops: 29, accuracy: 0.81),
            ],
            "validation": [
              EchopsWithAccuracyModel(echops: 0, accuracy: 0.38),
              EchopsWithAccuracyModel(echops: 1, accuracy: 0.56),
              EchopsWithAccuracyModel(echops: 2, accuracy: 0.60),
              EchopsWithAccuracyModel(echops: 3, accuracy: 0.31),
              EchopsWithAccuracyModel(echops: 4, accuracy: 0.65),
              EchopsWithAccuracyModel(echops: 5, accuracy: 0.66),
              EchopsWithAccuracyModel(echops: 6, accuracy: 0.59),
              EchopsWithAccuracyModel(echops: 7, accuracy: 0.65),
              EchopsWithAccuracyModel(echops: 8, accuracy: 0.72),
              EchopsWithAccuracyModel(echops: 9, accuracy: 0.46),
              EchopsWithAccuracyModel(echops: 10, accuracy: 0.75),
              EchopsWithAccuracyModel(echops: 11, accuracy: 0.73),
              EchopsWithAccuracyModel(echops: 12, accuracy: 0.73),
              EchopsWithAccuracyModel(echops: 13, accuracy: 0.74),
              EchopsWithAccuracyModel(echops: 14, accuracy: 0.71),
              EchopsWithAccuracyModel(echops: 15, accuracy: 0.63),
              EchopsWithAccuracyModel(echops: 16, accuracy: 0.62),
              EchopsWithAccuracyModel(echops: 17, accuracy: 0.67),
              EchopsWithAccuracyModel(echops: 18, accuracy: 0.75),
              EchopsWithAccuracyModel(echops: 19, accuracy: 0.75),
              EchopsWithAccuracyModel(echops: 20, accuracy: 0.77),
              EchopsWithAccuracyModel(echops: 21, accuracy: 0.67),
              EchopsWithAccuracyModel(echops: 22, accuracy: 0.56),
              EchopsWithAccuracyModel(echops: 23, accuracy: 0.74),
              EchopsWithAccuracyModel(echops: 24, accuracy: 0.78),
              EchopsWithAccuracyModel(echops: 25, accuracy: 0.76),
              EchopsWithAccuracyModel(echops: 26, accuracy: 0.60),
              EchopsWithAccuracyModel(echops: 27, accuracy: 0.52),
              EchopsWithAccuracyModel(echops: 28, accuracy: 0.76),
              EchopsWithAccuracyModel(echops: 29, accuracy: 0.77),
            ]
          },
          chartTitle: "Train vs Validation Accuracy",
        ),
        MLDataModel(
          index: 1,
          title: "CNN-30",
          label1: "train",
          label2: "validation",
          lineChartmodelData: {
            "train": [
              EchopsWithAccuracyModel(echops: 29, accuracy: 1.01),
              EchopsWithAccuracyModel(echops: 28, accuracy: 0.93),
              EchopsWithAccuracyModel(echops: 27, accuracy: 0.85),
              EchopsWithAccuracyModel(echops: 26, accuracy: 0.80),
              EchopsWithAccuracyModel(echops: 25, accuracy: 0.77),
              EchopsWithAccuracyModel(echops: 24, accuracy: 0.73),
              EchopsWithAccuracyModel(echops: 23, accuracy: 0.71),
              EchopsWithAccuracyModel(echops: 22, accuracy: 0.66),
              EchopsWithAccuracyModel(echops: 21, accuracy: 0.66),
              EchopsWithAccuracyModel(echops: 20, accuracy: 0.66),
              EchopsWithAccuracyModel(echops: 19, accuracy: 0.62),
              EchopsWithAccuracyModel(echops: 18, accuracy: 0.63),
              EchopsWithAccuracyModel(echops: 17, accuracy: 0.61),
              EchopsWithAccuracyModel(echops: 16, accuracy: 0.60),
              EchopsWithAccuracyModel(echops: 15, accuracy: 0.57),
              EchopsWithAccuracyModel(echops: 14, accuracy: 0.54),
              EchopsWithAccuracyModel(echops: 13, accuracy: 0.55),
              EchopsWithAccuracyModel(echops: 12, accuracy: 0.54),
              EchopsWithAccuracyModel(echops: 11, accuracy: 0.57),
              EchopsWithAccuracyModel(echops: 10, accuracy: 0.53),
              EchopsWithAccuracyModel(echops: 9, accuracy: 0.54),
              EchopsWithAccuracyModel(echops: 8, accuracy: 0.51),
              EchopsWithAccuracyModel(echops: 7, accuracy: 0.52),
              EchopsWithAccuracyModel(echops: 6, accuracy: 0.52),
              EchopsWithAccuracyModel(echops: 5, accuracy: 0.51),
              EchopsWithAccuracyModel(echops: 4, accuracy: 0.52),
              EchopsWithAccuracyModel(echops: 3, accuracy: 0.51),
              EchopsWithAccuracyModel(echops: 2, accuracy: 0.51),
              EchopsWithAccuracyModel(echops: 1, accuracy: 0.51),
              EchopsWithAccuracyModel(echops: 0, accuracy: 0.50),
            ],
            "validation": [
              EchopsWithAccuracyModel(echops: 29, accuracy: 1.17),
              EchopsWithAccuracyModel(echops: 28, accuracy: 1.01),
              EchopsWithAccuracyModel(echops: 27, accuracy: 2.4),
              EchopsWithAccuracyModel(echops: 26, accuracy: 0.95),
              EchopsWithAccuracyModel(echops: 25, accuracy: 0.96),
              EchopsWithAccuracyModel(echops: 24, accuracy: 1.22),
              EchopsWithAccuracyModel(echops: 23, accuracy: 0.99),
              EchopsWithAccuracyModel(echops: 22, accuracy: 0.82),
              EchopsWithAccuracyModel(echops: 21, accuracy: 1.95),
              EchopsWithAccuracyModel(echops: 20, accuracy: 0.68),
              EchopsWithAccuracyModel(echops: 19, accuracy: 0.74),
              EchopsWithAccuracyModel(echops: 18, accuracy: 0.82),
              EchopsWithAccuracyModel(echops: 17, accuracy: 0.72),
              EchopsWithAccuracyModel(echops: 16, accuracy: 0.77),
              EchopsWithAccuracyModel(echops: 15, accuracy: 1.08),
              EchopsWithAccuracyModel(echops: 14, accuracy: 1.00),
              EchopsWithAccuracyModel(echops: 13, accuracy: 1.11),
              EchopsWithAccuracyModel(echops: 12, accuracy: 0.62),
              EchopsWithAccuracyModel(echops: 11, accuracy: 0.78),
              EchopsWithAccuracyModel(echops: 10, accuracy: 0.59),
              EchopsWithAccuracyModel(echops: 9, accuracy: 0.91),
              EchopsWithAccuracyModel(echops: 8, accuracy: 1.26),
              EchopsWithAccuracyModel(echops: 7, accuracy: 0.68),
              EchopsWithAccuracyModel(echops: 6, accuracy: 0.61),
              EchopsWithAccuracyModel(echops: 5, accuracy: 0.63),
              EchopsWithAccuracyModel(echops: 4, accuracy: 1.24),
              EchopsWithAccuracyModel(echops: 3, accuracy: 1.91),
              EchopsWithAccuracyModel(echops: 2, accuracy: 0.63),
              EchopsWithAccuracyModel(echops: 1, accuracy: 0.59),
              EchopsWithAccuracyModel(echops: 0, accuracy: 0.60),
            ]
          },
          chartTitle: "Train vs Validation Loss",
        ),
      ],
    },
    {
      "title": "Resnet",
      "modelData": [
        MLDataModel(
          index: 2,
          title: "Resnet",
          label1: "train",
          label2: "validation",
          lineChartmodelData: {
            "train": [
              EchopsWithAccuracyModel(echops: 0, accuracy: 0.26),
              EchopsWithAccuracyModel(echops: 1, accuracy: 0.29),
              EchopsWithAccuracyModel(echops: 2, accuracy: 0.31),
              EchopsWithAccuracyModel(echops: 3, accuracy: 0.33),
              EchopsWithAccuracyModel(echops: 4, accuracy: 0.34),
              EchopsWithAccuracyModel(echops: 5, accuracy: 0.35),
              EchopsWithAccuracyModel(echops: 6, accuracy: 0.38),
              EchopsWithAccuracyModel(echops: 7, accuracy: 0.38),
              EchopsWithAccuracyModel(echops: 8, accuracy: 0.38),
              EchopsWithAccuracyModel(echops: 9, accuracy: 0.39),
              EchopsWithAccuracyModel(echops: 10, accuracy: 0.40),
              EchopsWithAccuracyModel(echops: 11, accuracy: 0.40),
              EchopsWithAccuracyModel(echops: 12, accuracy: 0.40),
              EchopsWithAccuracyModel(echops: 13, accuracy: 0.41),
              EchopsWithAccuracyModel(echops: 14, accuracy: 0.41),
              EchopsWithAccuracyModel(echops: 15, accuracy: 0.44),
              EchopsWithAccuracyModel(echops: 16, accuracy: 0.42),
              EchopsWithAccuracyModel(echops: 17, accuracy: 0.43),
              EchopsWithAccuracyModel(echops: 18, accuracy: 0.44),
              EchopsWithAccuracyModel(echops: 19, accuracy: 0.44),
            ],
            "validation": [
              EchopsWithAccuracyModel(echops: 0, accuracy: 0.30),
              EchopsWithAccuracyModel(echops: 1, accuracy: 0.30),
              EchopsWithAccuracyModel(echops: 2, accuracy: 0.33),
              EchopsWithAccuracyModel(echops: 3, accuracy: 0.37),
              EchopsWithAccuracyModel(echops: 4, accuracy: 0.36),
              EchopsWithAccuracyModel(echops: 5, accuracy: 0.38),
              EchopsWithAccuracyModel(echops: 6, accuracy: 0.38),
              EchopsWithAccuracyModel(echops: 7, accuracy: 0.38),
              EchopsWithAccuracyModel(echops: 8, accuracy: 0.36),
              EchopsWithAccuracyModel(echops: 9, accuracy: 0.43),
              EchopsWithAccuracyModel(echops: 10, accuracy: 0.41),
              EchopsWithAccuracyModel(echops: 11, accuracy: 0.41),
              EchopsWithAccuracyModel(echops: 12, accuracy: 0.41),
              EchopsWithAccuracyModel(echops: 13, accuracy: 0.40),
              EchopsWithAccuracyModel(echops: 14, accuracy: 0.44),
              EchopsWithAccuracyModel(echops: 15, accuracy: 0.42),
              EchopsWithAccuracyModel(echops: 16, accuracy: 0.42),
              EchopsWithAccuracyModel(echops: 17, accuracy: 0.44),
              EchopsWithAccuracyModel(echops: 18, accuracy: 0.44),
              EchopsWithAccuracyModel(echops: 19, accuracy: 0.45),
            ]
          },
          chartTitle: "Train vs Validation Accuracy",
        ),
        MLDataModel(
          index: 2,
          title: "Resnet",
          label1: "train",
          label2: "validation",
          lineChartmodelData: {
            "train": [
              EchopsWithAccuracyModel(echops: 19, accuracy: 1.76),
              EchopsWithAccuracyModel(echops: 18, accuracy: 1.70),
              EchopsWithAccuracyModel(echops: 17, accuracy: 1.65),
              EchopsWithAccuracyModel(echops: 16, accuracy: 1.63),
              EchopsWithAccuracyModel(echops: 15, accuracy: 1.62),
              EchopsWithAccuracyModel(echops: 14, accuracy: 1.61),
              EchopsWithAccuracyModel(echops: 13, accuracy: 1.55),
              EchopsWithAccuracyModel(echops: 12, accuracy: 1.52),
              EchopsWithAccuracyModel(echops: 11, accuracy: 1.54),
              EchopsWithAccuracyModel(echops: 10, accuracy: 1.50),
              EchopsWithAccuracyModel(echops: 9, accuracy: 1.44),
              EchopsWithAccuracyModel(echops: 8, accuracy: 1.49),
              EchopsWithAccuracyModel(echops: 7, accuracy: 1.47),
              EchopsWithAccuracyModel(echops: 6, accuracy: 1.46),
              EchopsWithAccuracyModel(echops: 5, accuracy: 1.45),
              EchopsWithAccuracyModel(echops: 4, accuracy: 1.44),
              EchopsWithAccuracyModel(echops: 3, accuracy: 1.43),
              EchopsWithAccuracyModel(echops: 2, accuracy: 1.43),
              EchopsWithAccuracyModel(echops: 1, accuracy: 1.42),
              EchopsWithAccuracyModel(echops: 0, accuracy: 1.42),
            ],
            "validation": [
              EchopsWithAccuracyModel(echops: 19, accuracy: 1.71),
              EchopsWithAccuracyModel(echops: 18, accuracy: 1.70),
              EchopsWithAccuracyModel(echops: 17, accuracy: 1.64),
              EchopsWithAccuracyModel(echops: 16, accuracy: 1.60),
              EchopsWithAccuracyModel(echops: 15, accuracy: 1.58),
              EchopsWithAccuracyModel(echops: 14, accuracy: 1.56),
              EchopsWithAccuracyModel(echops: 13, accuracy: 1.52),
              EchopsWithAccuracyModel(echops: 12, accuracy: 1.5),
              EchopsWithAccuracyModel(echops: 11, accuracy: 1.54),
              EchopsWithAccuracyModel(echops: 10, accuracy: 1.49),
              EchopsWithAccuracyModel(echops: 9, accuracy: 1.50),
              EchopsWithAccuracyModel(echops: 8, accuracy: 1.43),
              EchopsWithAccuracyModel(echops: 7, accuracy: 1.42),
              EchopsWithAccuracyModel(echops: 6, accuracy: 1.42),
              EchopsWithAccuracyModel(echops: 5, accuracy: 1.43),
              EchopsWithAccuracyModel(echops: 4, accuracy: 1.46),
              EchopsWithAccuracyModel(echops: 3, accuracy: 1.48),
              EchopsWithAccuracyModel(echops: 2, accuracy: 1.40),
              EchopsWithAccuracyModel(echops: 1, accuracy: 1.41),
              EchopsWithAccuracyModel(echops: 0, accuracy: 1.41),
            ]
          },
          chartTitle: "Train vs Validation Loss",
        ),
      ],
    },
    {
      "title": "Mobile Net",
      "modelData": [
        MLDataModel(
          index: 3,
          title: "Mobile Net",
          label1: "train",
          label2: "validation",
          lineChartmodelData: {
            "train": [
              EchopsWithAccuracyModel(echops: 0, accuracy: 0.2041),
              EchopsWithAccuracyModel(echops: 1, accuracy: 0.2234),
              EchopsWithAccuracyModel(echops: 2, accuracy: 0.2234),
              EchopsWithAccuracyModel(echops: 3, accuracy: 0.2232),
              EchopsWithAccuracyModel(echops: 4, accuracy: 0.2227),
              EchopsWithAccuracyModel(echops: 5, accuracy: 0.2243),
              EchopsWithAccuracyModel(echops: 6, accuracy: 0.2234),
              EchopsWithAccuracyModel(echops: 7, accuracy: 0.2236),
              EchopsWithAccuracyModel(echops: 8, accuracy: 0.2234),
              EchopsWithAccuracyModel(echops: 9, accuracy: 0.2236),
              EchopsWithAccuracyModel(echops: 10, accuracy: 0.2236),
              EchopsWithAccuracyModel(echops: 11, accuracy: 0.2227),
              EchopsWithAccuracyModel(echops: 12, accuracy: 0.2225),
              EchopsWithAccuracyModel(echops: 13, accuracy: 0.2243),
              EchopsWithAccuracyModel(echops: 14, accuracy: 0.2236),
              EchopsWithAccuracyModel(echops: 15, accuracy: 0.2234),
              EchopsWithAccuracyModel(echops: 16, accuracy: 0.2232),
              EchopsWithAccuracyModel(echops: 17, accuracy: 0.2241),
              EchopsWithAccuracyModel(echops: 18, accuracy: 0.2229),
              EchopsWithAccuracyModel(echops: 19, accuracy: 0.2241),
            ],
            "validation": [
              EchopsWithAccuracyModel(echops: 0, accuracy: 0.2207),
              EchopsWithAccuracyModel(echops: 1, accuracy: 0.2246),
              EchopsWithAccuracyModel(echops: 2, accuracy: 0.2226),
              EchopsWithAccuracyModel(echops: 3, accuracy: 0.2226),
              EchopsWithAccuracyModel(echops: 4, accuracy: 0.2265),
              EchopsWithAccuracyModel(echops: 5, accuracy: 0.2187),
              EchopsWithAccuracyModel(echops: 6, accuracy: 0.2246),
              EchopsWithAccuracyModel(echops: 7, accuracy: 0.2246),
              EchopsWithAccuracyModel(echops: 8, accuracy: 0.2226),
              EchopsWithAccuracyModel(echops: 9, accuracy: 0.2187),
              EchopsWithAccuracyModel(echops: 10, accuracy: 0.2246),
              EchopsWithAccuracyModel(echops: 11, accuracy: 0.2246),
              EchopsWithAccuracyModel(echops: 12, accuracy: 0.2187),
              EchopsWithAccuracyModel(echops: 13, accuracy: 0.2265),
              EchopsWithAccuracyModel(echops: 14, accuracy: 0.2304),
              EchopsWithAccuracyModel(echops: 15, accuracy: 0.2265),
              EchopsWithAccuracyModel(echops: 16, accuracy: 0.2246),
              EchopsWithAccuracyModel(echops: 17, accuracy: 0.2207),
              EchopsWithAccuracyModel(echops: 18, accuracy: 0.2226),
              EchopsWithAccuracyModel(echops: 19, accuracy: 0.2148),
            ]
          },
          chartTitle: "Train vs Validation Accuracy",
        ),
        MLDataModel(
          index: 3,
          title: "Mobile Net",
          label1: "train",
          label2: "validation",
          lineChartmodelData: {
            "train": [
              EchopsWithAccuracyModel(echops: 19, accuracy: 2.5198),
              EchopsWithAccuracyModel(echops: 18, accuracy: 1.8043),
              EchopsWithAccuracyModel(echops: 17, accuracy: 1.7813),
              EchopsWithAccuracyModel(echops: 16, accuracy: 1.7788),
              EchopsWithAccuracyModel(echops: 15, accuracy: 1.7774),
              EchopsWithAccuracyModel(echops: 14, accuracy: 1.7758),
              EchopsWithAccuracyModel(echops: 13, accuracy: 1.7756),
              EchopsWithAccuracyModel(echops: 12, accuracy: 1.7753),
              EchopsWithAccuracyModel(echops: 11, accuracy: 1.7749),
              EchopsWithAccuracyModel(echops: 10, accuracy: 1.7750),
              EchopsWithAccuracyModel(echops: 9, accuracy: 1.7750),
              EchopsWithAccuracyModel(echops: 8, accuracy: 1.7754),
              EchopsWithAccuracyModel(echops: 7, accuracy: 1.7754),
              EchopsWithAccuracyModel(echops: 6, accuracy: 1.7748),
              EchopsWithAccuracyModel(echops: 5, accuracy: 1.7749),
              EchopsWithAccuracyModel(echops: 4, accuracy: 1.7750),
              EchopsWithAccuracyModel(echops: 3, accuracy: 1.7751),
              EchopsWithAccuracyModel(echops: 2, accuracy: 1.7747),
              EchopsWithAccuracyModel(echops: 1, accuracy: 1.7754),
              EchopsWithAccuracyModel(echops: 0, accuracy: 1.7749),
            ],
            "validation": [
              EchopsWithAccuracyModel(echops: 19, accuracy: 1.7879),
              EchopsWithAccuracyModel(echops: 18, accuracy: 1.7832),
              EchopsWithAccuracyModel(echops: 17, accuracy: 1.7797),
              EchopsWithAccuracyModel(echops: 16, accuracy: 1.7776),
              EchopsWithAccuracyModel(echops: 15, accuracy: 1.7762),
              EchopsWithAccuracyModel(echops: 14, accuracy: 1.7771),
              EchopsWithAccuracyModel(echops: 13, accuracy: 1.7742),
              EchopsWithAccuracyModel(echops: 12, accuracy: 1.7742),
              EchopsWithAccuracyModel(echops: 11, accuracy: 1.7753),
              EchopsWithAccuracyModel(echops: 10, accuracy: 1.7781),
              EchopsWithAccuracyModel(echops: 9, accuracy: 1.7747),
              EchopsWithAccuracyModel(echops: 8, accuracy: 1.7722),
              EchopsWithAccuracyModel(echops: 7, accuracy: 1.7757),
              EchopsWithAccuracyModel(echops: 6, accuracy: 1.7736),
              EchopsWithAccuracyModel(echops: 5, accuracy: 1.7721),
              EchopsWithAccuracyModel(echops: 4, accuracy: 1.7731),
              EchopsWithAccuracyModel(echops: 3, accuracy: 1.7731),
              EchopsWithAccuracyModel(echops: 2, accuracy: 1.7762),
              EchopsWithAccuracyModel(echops: 1, accuracy: 1.7757),
              EchopsWithAccuracyModel(echops: 0, accuracy: 1.7783),
            ]
          },
          chartTitle: "Train vs Validation Loss",
        ),
      ],
    },
  ];

  @override
  Widget build(BuildContext context) {
    final appTextTheme = Theme.of(context).extension<AppTextTheme>()!;

    return Scaffold(
      appBar: CustomAppBar(
        title: LocaleKeys.dashBoard.tr(),
      ),
      body: Padding(
        padding: EdgeInsets.all(12.wp),
        child: GridView.builder(
          itemCount: modelDetailList.length,
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            mainAxisSpacing: 20,
            crossAxisSpacing: 20,
          ),
          itemBuilder: (context, index) {
            return GestureDetector(
              onTap: () {
                Navigator.pushNamed(
                  context,
                  Routes.modelDetail,
                  arguments: modelDetailList[index]["modelData"],
                );
              },
              child: Card(
                color: AppColors.grey.withOpacity(0.1),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Padding(
                  padding: const EdgeInsets.all(12),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      SizedBox(
                        height: 20.hp,
                      ),
                      const Icon(
                        LucideIcons.lineChart,
                        color: AppColors.goldenColor,
                        size: 50,
                      ),
                      SizedBox(
                        height: 50.hp,
                      ),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            modelDetailList[index]["title"] ?? "",
                            style: appTextTheme.bodyLargeSemiBold
                                .copyWith(fontSize: 20.wp),
                          ),
                          const Icon(
                            LucideIcons.chevronRight,
                            color: AppColors.goldenColor,
                            size: 26,
                          ),
                        ],
                      )
                    ],
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
